OHDSI/PhenotypeR

- R/cohortDiagnostics.R
> remove addDemographics

- R/codelistDiagnostics.R
- tests/testthat/test-dbms.R
- vignettes/a02_CodelistDiagnostics.Rmd
index event breakdown even without achilles
> reorganise codelistdiagnostics

- R/reexports.R
> add funs to reexport

- R/shinyDiagnostics.R
> default order

- R/phenotypeDiagnostics.R
> more cli progress updates

- README.Rmd
- README.md
> readme update

- inst/shiny/global.R
- inst/shiny/scripts/preprocess.R
- inst/shiny/server.R
- inst/shiny/ui.R
> fix lsc comparison

- inst/shiny/server.R
- inst/shiny/ui.R
> achilles code use

- R/cohortDiagnostics.R
- R/matchedDiagnostics.R
- R/phenotypeDiagnostics.R
- R/shinyDiagnostics.R
- inst/shiny/scripts/preprocess.R
- inst/shiny/server.R
- inst/shiny/ui.R
- man/cohortDiagnostics.Rd
- man/matchedDiagnostics.Rd
- man/phenotypeDiagnostics.Rd
- man/shinyDiagnostics.Rd
- tests/testthat/test-cohortDiagnostics.R
- tests/testthat/test-databaseDiagnostics.R
- tests/testthat/test-matchedDiagnostics.R
- tests/testthat/test-phenotypeDiagnostics.R
- tests/testthat/test-shinyDiagnostics.R
> include source in lsc

- inst/shiny/server.R
> descending order by percentage

- inst/shiny/global.R
- inst/shiny/server.R
> Speedy compare

- inst/shiny/ui.R
> Remove left tab in lsc

- R/addCodelistAttribute.R
- R/codelistDiagnostics.R
- R/cohortDiagnostics.R
- R/databaseDiagnostics.R
- R/matchedDiagnostics.R
- R/phenotypeDiagnostics.R
- R/populationDiagnostics.R
- R/shinyDiagnostics.R
Check addCodelistAttribute and codelistDiagnostics examples
> Check examples

- R/cohortDiagnostics.R
- tests/testthat/test-cohortDiagnostics.R
> Group age distribution by cohort

- .gitignore
- DESCRIPTION
- inst/shiny/global.R
- inst/shiny/server.R
- inst/shiny/ui.R
> Add age distribution plot

- inst/shiny/scripts/preprocess.R
- inst/shiny/server.R
> Update matched and sampled names

- inst/shiny/global.R
- inst/shiny/server.R
- inst/shiny/ui.R
> Add plotPopulationIncidence() and plotPopulationPrevalence

- DESCRIPTION
- inst/shiny/global.R
- inst/shiny/server.R
- inst/shiny/ui.R
> Fix download buttons

- inst/shiny/scripts/preprocess.R
- inst/shiny/server.R
- inst/shiny/ui.R
> Arrange lsc top concepts

- inst/shiny/global.R
- inst/shiny/server.R
> median for all and extra validation

- inst/shiny/ui.R
> add ui elements

- inst/shiny/server.R
> download raw data

- inst/shiny/server.R
- inst/shiny/ui.R
> plot interactive option

- inst/shiny/server.R
- inst/shiny/ui.R
> use reactable for lsc

- inst/shiny/global.R
> use separators for counts

- inst/shiny/global.R
- inst/shiny/server.R
- inst/shiny/ui.R
> Add interquantile range lines button

- inst/shiny/global.R
- inst/shiny/scripts/preprocess.R
- inst/shiny/server.R
> Fix bug in age distribution

- inst/shiny/server.R
- inst/shiny/ui.R
fix prevalence plot rounding
don't plot zero for incidence
> inc prev tweaks

- vignettes/a01_DatabaseDiagnostics.Rmd
- vignettes/a02_CodelistDiagnostics.Rmd
- vignettes/a03_CohortDiagnostics.Rmd
- vignettes/a04_MatchedDiagnostics.Rmd
- vignettes/a05_PopulationDiagnostics.Rmd
> db diag vignette

- vignettes/a01_DatabaseDiagnostics.Rmd
- vignettes/a02_CodelistDiagnostics.Rmd
- vignettes/a03_CohortDiagnostics.Rmd
- vignettes/a04_MatchedDiagnostics.Rmd
- vignettes/a05_PopulationDiagnostics.Rmd
remove snake case for compatability with new CDMConnector
closes #290
> eunomiaIsAvailable

- R/codelistDiagnostics.R
- vignettes/a02_CodelistDiagnostics.Rmd
> Document missing codelist attribute

- R/codelistDiagnostics.R
- tests/testthat/test-codelistDiagnostics.R
> Check empty cohorts before summariseCohortCodeUse()

- R/cohortDiagnostics.R
- inst/shiny/server.R
- inst/shiny/ui.R
> Add cohort count

- R/codelistDiagnostics.R
- R/cohortDiagnostics.R
- tests/testthat/test-codelistDiagnostics.R
> Accept duplicated codelists if they are the same

- R/shinyDiagnostics.R
> When directory "shiny" exists, ask if the user wants to overwrite it

- inst/shiny/global.R
> Fix age distribution plot

- .gitignore
- inst/shiny/global.R
Fixes #321 as it works with these version of the packages
> Update packages versions

- inst/shiny/server.R
- inst/shiny/ui.R
- Added the option to specify the top number of concepts
- Allow to plot more than one cohort attrition
> Couple of changes

- inst/shiny/ui.R
> summarise cohort count fix filtering error

- .gitignore
- DESCRIPTION
- R/cohortDiagnostics.R
- R/mockPhenotypeR.R
- inst/shiny/global.R
- inst/shiny/scripts/preprocess.R
- inst/shiny/server.R
- inst/shiny/ui.R
- tests/testthat/test-cohortDiagnostics.R
> Add survival analysis

- inst/shiny/server.R
> Add progress bar

- inst/shiny/global.R
> Check versions before loading them

- inst/shiny/global.R
> Ask if preprocess wants to be re-run

- DESCRIPTION
- inst/shiny/global.R
> Require shiny > 1.11.1

- .gitignore
- R/shinyDiagnostics.R
- inst/shiny/data/raw/readme.md
- inst/shiny/data/readme.md
In the future `folderName` could be a parameter.
Relates to https://github.com/OHDSI/OmopSketch/issues/423
> Custom shiny name

- _pkgdown.yml
- vignettes/phenotypeExpectations.Rmd
> expectations vignette

- inst/shiny/global.R
- inst/shiny/server.R
- inst/shiny/ui.R
> include cohort expectations in shiny

- R/getCohortExpectations.R
- inst/shiny/global.R
- inst/shiny/server.R
- inst/shiny/ui.R
> Filter expectations by diagnostic

- R/codelistDiagnostics.R
- R/cohortDiagnostics.R
- R/databaseDiagnostics.R
- R/populationDiagnostics.R
- R/shinyDiagnostics.R
- man/codelistDiagnostics.Rd
- tests/testthat/test-codelistDiagnostics.R
- tests/testthat/test-cohortDiagnostics.R
- tests/testthat/test-databaseDiagnostics.R
- tests/testthat/test-populationDiagnostics.R
- tests/testthat/test-shinyDiagnostics.R
> Add PhenotypeR in settings

- .gitignore
- R/shinyDiagnostics.R
- inst/shiny/data/raw/expectations/readme.md
- inst/shiny/scripts/functions.R
- inst/shiny/scripts/preprocess.R
- inst/shiny/server.R
- inst/shiny/ui.R
- tests/testthat/test-shinyDiagnostics.R
Fixes #320
(PR with only main tabs)
> Eliminate tabs that are not used

- R/mockPhenotypeR.R
> Add achilles tables to mockPhenotypeR

- inst/shiny/scripts/preprocess.R
> Typo in preprocess

- README.Rmd
- vignettes/ShinyDiagnostics.Rmd
> Create ShinyDiagnostics vignette using TANGO

- inst/shiny/scripts/preprocess.R
> Arrange cohort, cdm names, and codelists name in alphabetical order

- inst/shiny/global.R
> add filter in plotAgeDensity()
